### ISSUE TITLE
Autoupdate Electron App

### ISSUE THREAD

**Issue by bcomnes** [ipfs/station#14]
- [ ] Implement Electrons built in updater: https://github.com/atom/electron/blob/master/docs/api/auto-updater.md
- [ ] Figure out linux and windows solutions
- [ ] Distribute bins via IPFS itself

**Comment by Dignifiedquire** [comment]
Looks like this works cross platform: https://github.com/EvolveLabs/electron-updater

**Comment by jbenet** [comment]
nice, :+1:

**Comment by bcomnes** [comment]
Nice find!

**Comment by bcomnes** [comment]
Cleaning up old issues I opened.  I don't really have the bw for this right now, so feel free to reopen or recreate if you still want this issue.
