### ISSUE TITLE
Timeout on 'npm install'

### ISSUE THREAD

**Issue by ARezaK** [ipfs/station#213]
Using osx I've been unable to complete 'npm install'. Using a verbose tag I receive this error:

npm info retry will retry, error on last attempt: Error: socket hang up

Just for fun I updated package.json to the latest versions and I had no error doing an npm install. Npm start wouldn't work though for probably obvious reasons. Anything I can do to narrow down the problem?

**Comment by diasdavid** [comment]
@ARezaK that seems like a `npm` error. which version of `npm` are you using?

**Comment by ARezaK** [comment]
npm -v gives me
3.8.5

**Comment by diasdavid** [comment]
can you install modules in other projects?

**Comment by ARezaK** [comment]
sure can. Tried out a couple different projects and everything worked fine. And I mentioned in op that if I update the package.json to the latest versions it seems to break the project but npm install works.

**Comment by ARezaK** [comment]
Do you know if its possible to isolate what npm package its hanging up on?

**Comment by ARezaK** [comment]
Looks like the last pull request fixed the problem
