### ISSUE TITLE
station cannot compile on node v6.0 until babel is updated

### ISSUE THREAD

**Issue by swang** [ipfs/station#281]
See: babel/babel#3448:

Until station is updated accordingly, running `npm run build` in node v6.0 will cause errors: https://gist.github.com/swang/6ac9c3bd5c20ead6540e4cad6719ae66

The solution I used is to revert back to node v5.0 using nvm. babel released 6.9.x but npm still seems to only have 6.5.x.

**Comment by dignifiedquire** [comment]
I've been running babel in other projects fine with node 6 after updating to the latest versions on npm. So it's just a matter of upgrading things here.

**Comment by dignifiedquire** [comment]
@swang I have a PR in progress that will fix this: #282 Just need to update some dependencies first to make sure all things are smooth and up to date.

**Comment by dignifiedquire** [comment]
Babel is updated to the latest version, works fine now with node 6
