### ISSUE TITLE
[packaging] Do not fork bomb

### ISSUE THREAD

**Issue by Dignifiedquire** [ipfs/station#53]
At the moment starting the packaged version (at least on OS X) results in the app fork bombing the machine. Ideas, helps and suggestions are very welcome!

**Comment by jbenet** [comment]
lol :( :-1:

**Comment by Dignifiedquire** [comment]
@jbenet found the reason, it is you :stuck_out_tongue_closed_eyes: https://github.com/jbenet/node-subcomandante/issues/2

**Comment by Dignifiedquire** [comment]
Fixed :)
