### ISSUE TITLE
npm install gives epeerinvalid warning

### ISSUE THREAD

**Issue by luisbebop** [ipfs/station#56]
`npm WARN EPEERINVALID react-file-drop@0.1.5 requires a peer of react@^0.13 || 0.14.0-beta1 but none was installed.`

node v4.1.1
npm 3.3.6

**Comment by Dignifiedquire** [comment]
The install is not failing, it's just a warning. Reference issue: https://github.com/sarink/react-file-drop/issues/3

**Comment by luisbebop** [comment]
Thanks

**Comment by diasdavid** [comment]
@Dignifiedquire maybe add this to a installation notes in the README?

**Comment by namick** [comment]
For me the install is failing:
```
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@0.14.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-addons-css-transition-group@0.14.0 wants react@^0.14.0
npm ERR! peerinvalid Peer react-file-drop@0.1.6 wants react@^0.13 || 0.14.0-beta1
npm ERR! peerinvalid Peer react-widgets@3.0.0 wants react@^0.14.0
npm ERR! peerinvalid Peer redbox-react@1.1.1 wants react@>=0.13.2 || ^0.14.0-rc1
```
I can get it to install and work correctly if I edit `node_modules/react-file-drop/package.json` and `node_modules/redbox-react/package.json`  removing the `-beta1` and `-rc1` respectively.

**Comment by Dignifiedquire** [comment]
If you upgrade to `npm@3` the install will work

**Comment by diasdavid** [comment]
@Dignifiedquire might be worth to add that info to the README.md, seems that there is a considerable amount of people hitting the npm 2 vs 3 problem

**Comment by namick** [comment]
npm 3 works for me.  Thanks.  I updated the README in a PR.
