### ISSUE TITLE
Windowing/Tray UX

### ISSUE THREAD

**Issue by bcomnes** [ipfs/station#8]
Thinking this would best work as primarily a Tray app (e.g. Menu bar for OS X, Notification Tray Windows/Linux).
- [x] App permanently lives in the tray at all times
- [x] When the app window is open, a dock/task bar icon will open.
- [x] When the app window is closed, the dock/task bar icon is hidden, and the app lives in the tray.
- [x] Enable silent launching to the tray so that people can add the app to their startup apps
- [ ] Indicate running/stopped status of the ipfs daemon via the tray (and dock?) icon.

I think this flow would help increase people running as peers in the background without having to think about it too much.

**Comment by jbenet** [comment]
> - App permanently lives in the tray at all times
SGTM
> - When the app window is open, a dock/task bar icon will open.
SGTM
> - When the app window is closed, the dock/task bar icon is hidden, and the app lives in the tray.
SGTM
> - Enable silent launching to the tray so that people can add the app to their startup apps
SGTM

I think that the menubar item should stay there and let you turn IPFS daemon on and off. menubar/tray item stays (unless you ask it to not show)). the logo can change to reflect whether ipfs is running or not, more grayed out when it's off, or whatever.

**Comment by bcomnes** [comment]
Ohh good point.  Offline access to files is important as is quick access to starting/stopping the daemon when peering is inappropriate.

**Comment by jbenet** [comment]
oh we could also have a "daemon online but disconnected" mode.

**Comment by krl** [comment]
Most of these things were already addressed, but only seems to work properly when the app is run as a package. This should be ok imo.


open:
![open](https://cloud.githubusercontent.com/assets/59379/8132870/fcd72378-1124-11e5-8972-3307910a1e71.png)

minimized:
![minimized](https://cloud.githubusercontent.com/assets/59379/8132877/053c5182-1125-11e5-93b1-4a6899b7d1bb.png)

closed:
![closed](https://cloud.githubusercontent.com/assets/59379/8132878/0a86be84-1125-11e5-9f69-1bf80cfecf5d.png)

**Comment by jbenet** [comment]
seems to work on osx, too. \o/ gj

- considering whether it should use a repo _in_ the app bundle? (so when people trash ipfs, it deletes everything? but then again maybe not. not sure, maybe best to keep it in default location)  cc @bcomnes thoughts?

- it's using my `$HOME` repo (`~/.ipfs`), but not clashing with a daemon i have running... (maybe the electron-app daemon is failing to bind ports and it just "happens" to work cause the ports are the same?)

- also, if i move my repo away (i.e. no `~/.ipfs`), launching the electron-ipfs.app doesnt do anything. maybe stuck somewhere? (is wizard supposed to appear here?)

**Comment by bcomnes** [comment]
¯\_(ツ)_/¯  I think keeping node data in the app bundle is the wrong place to keep it.  I like using `~/.ipfs` but  we may consider using system sanctioned locations for data like `~/Library/Application Support`

**Comment by jbenet** [comment]
We could let the user choose when it launches, maybe between:

> - [x] IPFS Default: `/Users/<user>/.ipfs`
> - [ ] System Default: `/Users/<user>/Library/Application Support`
> - [ ] Custom: [______________________]

**Comment by Dignifiedquire** [comment]
@bcomnes @jbenet can you please check the latest version, and update the issue accordingly?

**Comment by jbenet** [comment]
Need to verify it works fine on:
- [ ] Linux - @krl ?
- [ ] OSX - @diasdavid ?
- [ ] Windows - @gatesvp @Mithgol ?

(what's your OS @Dignifiedquire @bcomnes ?)

**Comment by Dignifiedquire** [comment]
I have OS X and window in a vm

**Comment by diasdavid** [comment]
works fine for me on OSX (and sent a shout to some more devs that are big fans of React and WebPack :)

**Comment by Mithgol** [comment]
I assume we are talking about https://github.com/ipfs/station

As its README recommends, I've cloned the repo and run `npm install`.

I've watched it running for an hour and installing 869 dependencies in `node_modules\.staging` and then I've forced it to quit because I had to go.

Ideas:

* Maybe it should be recommended to run `npm install --production` instead of `npm install`.

* Maybe a pre-built version should be distributed as a single archive to reduce the overhead of downloading hundreds of dependencies.

**Comment by whyrusleeping** [comment]
@Mithgol a prebuilt binary will be provided for users once the project is ready for release.

**Comment by Mithgol** [comment]
The file `package.json` also assumes a non-Windows system where it uses [`NODE_ENV=production some_command`](https://github.com/ipfs/station/blob/8328642c6fead515d5ed2fc634d8d31a6bebef78/package.json#L72-L74) because that syntax ([AFAIK](http://www.urbandictionary.com/define.php?term=afaik "as far as I know")) is not supported by the command line of Windows.

**Comment by bcomnes** [comment]
https://github.com/ForbesLindesay/win-spawn is a commonly recommended way to route around that issue, however I find that it doesn't always noop on unix systems like its supposed to.  It could be a matter of just squashing a bug though, I haven't had a chance to really look into it.
